#!/bin/bash
# Put this script in .git/hooks/pre-commit on a Mac to do automatic MD => PDF
# conversion at commit time. This file doesn't work in a different place,
# I'm just putting it in the repository itself for safekeeping!
set -euo pipefail
echo "I'm converting MarkDown => PDF for you <3"
echo "If something breaks, run 'git commit --no-verify ...'"
rootdir=$(git rev-parse --show-toplevel)

IFS=$'\n'       # make newlines the only separator
for markdown in $(git diff --cached --name-only | grep -E '.md$'); do
  echo "Converting $markdown..." >&2
  pdfname=$("$rootdir/scripts/md2pdf" "$markdown" 2>/dev/null)
  git add "$pdfname"
done
